#!/usr/bin/env python3
"""
DBC to Header Generator for VCU Project
Generates C header from DBC file with custom formatting
"""

import cantools
import sys

def generate_header_from_dbc(dbc_file, output_file):
    """Generate C header from DBC file"""
    
    # Load DBC
    try:
        db = cantools.database.load_file(dbc_file)
    except Exception as e:
        print(f"Error loading DBC file: {e}")
        return False
    
    # Generate header content
    header_content = f"""#ifndef {output_file.upper().replace('.', '_')}_H
#define {output_file.upper().replace('.', '_')}_H

#include <stdint.h>

// Auto-generated from {dbc_file}
// Generated by VCU DBC Generator

"""
    
    # Generate message ID defines
    header_content += "// Message IDs\n"
    for message in db.messages:
        define_name = f"{message.name.upper()}_ID"
        header_content += f"#define {define_name:<40} 0x{message.frame_id:03X}  // {message.frame_id}\n"
    
    header_content += "\n"
    
    # Generate signal information for each message
    for message in db.messages:
        header_content += f"// {message.name} (ID: 0x{message.frame_id:03X})\n"
        
        # Signal definitions as comments for reference
        for signal in message.signals:
            scale_str = f"scale={signal.scale}" if signal.scale != 1 else ""
            offset_str = f"offset={signal.offset}" if signal.offset != 0 else ""
            receiver_str = f"receiver={','.join(signal.receivers)}" if signal.receivers else ""
            
            info = ", ".join(filter(None, [scale_str, offset_str, receiver_str]))
            info_str = f" ({info})" if info else ""
            
            header_content += f"//   {signal.name}: {signal.start}|{signal.length}@{signal.byte_order}{'+' if not signal.is_signed else '-'}{info_str}\n"
        
        header_content += "\n"
    
    # Generate receiver-based routing information
    header_content += "// Receiver-based message routing\n"
    receivers = set()
    for message in db.messages:
        for signal in message.signals:
            receivers.update(signal.receivers)
    
    for receiver in sorted(receivers):
        header_content += f"// {receiver} receives:\n"
        for message in db.messages:
            has_signals = any(receiver in signal.receivers for signal in message.signals)
            if has_signals:
                header_content += f"//   - {message.name} (0x{message.frame_id:03X})\n"
        header_content += "\n"
    
    # Generate value tables
    header_content += "// Value definitions\n"
    for message in db.messages:
        for signal in message.signals:
            if signal.choices:
                header_content += f"// {signal.name} values:\n"
                for value, name in signal.choices.items():
                    define_name = f"{signal.name.upper()}_{name.upper().replace(' ', '_')}"
                    header_content += f"#define {define_name:<40} {value}\n"
                header_content += "\n"
    
    header_content += f"\n#endif // {output_file.upper().replace('.', '_')}_H\n"
    
    # Write to file
    try:
        with open(output_file, 'w') as f:
            f.write(header_content)
        print(f"Generated {output_file} from {dbc_file}")
        return True
    except Exception as e:
        print(f"Error writing output file: {e}")
        return False

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python dbc_to_header.py <input.dbc> <output.h>")
        sys.exit(1)
    
    dbc_file = sys.argv[1]
    output_file = sys.argv[2]
    
    if generate_header_from_dbc(dbc_file, output_file):
        print("Header generation successful!")
    else:
        print("Header generation failed!")
        sys.exit(1)