#!/usr/bin/env python3
"""
DBC to C Header Generator for VCU Project
Generates production-ready C headers from DBC files
"""

import re
import sys
import os

def parse_dbc_file(dbc_file):
    """Parse DBC file and extract basic information"""
    
    messages = []
    
    try:
        with open(dbc_file, 'r') as f:
            content = f.read()
    except Exception as e:
        print(f"Error reading DBC file: {e}")
        return None
    
    # Parse messages (BO_ lines)
    message_pattern = r'BO_\s+(\d+)\s+(\w+)\s*:\s*(\d+)\s+(\w+)'
    message_matches = re.findall(message_pattern, content)
    
    for match in message_matches:
        msg_id = int(match[0])
        msg_name = match[1]
        msg_size = int(match[2])
        msg_sender = match[3]
        
        # Find signals for this message
        signals = []
        
        # Look for signals after this message
        msg_start = content.find(f'BO_ {match[0]} {match[1]}')
        next_msg = content.find('BO_', msg_start + 1)
        if next_msg == -1:
            msg_section = content[msg_start:]
        else:
            msg_section = content[msg_start:next_msg]
        
        # Parse signals (SG_ lines)
        signal_pattern = r'SG_\s+(\w+)\s*:\s*(\d+)\|(\d+)@(\d+)([\+\-])\s*\(([^)]+)\)\s*\[([^\]]*)\]\s*"([^"]*)"\s*(.+)'
        signal_matches = re.findall(signal_pattern, msg_section)
        
        for sig_match in signal_matches:
            sig_name = sig_match[0]
            start_bit = int(sig_match[1])
            length = int(sig_match[2])
            byte_order = int(sig_match[3])
            signed = sig_match[4] == '-'
            scale_offset = sig_match[5].split(',')
            scale = float(scale_offset[0]) if len(scale_offset) > 0 else 1.0
            offset = float(scale_offset[1]) if len(scale_offset) > 1 else 0.0
            range_info = sig_match[6]
            unit = sig_match[7]
            receivers = [r.strip() for r in sig_match[8].split(',')]
            
            signals.append({
                'name': sig_name,
                'start_bit': start_bit,
                'length': length,
                'byte_order': byte_order,
                'signed': signed,
                'scale': scale,
                'offset': offset,
                'unit': unit,
                'receivers': receivers
            })
        
        messages.append({
            'id': msg_id,
            'name': msg_name,
            'size': msg_size,
            'sender': msg_sender,
            'signals': signals
        })
    
    return messages

def generate_header(messages, output_file, dbc_filename):
    """Generate production C header from parsed DBC data"""
    
    # Get base name for header guard
    base_name = os.path.splitext(os.path.basename(output_file))[0].upper()
    dbc_base_name = os.path.splitext(os.path.basename(dbc_filename))[0]
    
    header_content = f"""#ifndef {base_name}_H
#define {base_name}_H

#include <stdint.h>
#include <stdbool.h>

// Auto-generated from {dbc_filename}
// Generated by VCU DBC Parser - DO NOT EDIT MANUALLY

"""

    # Generate message ID defines
    header_content += "// Message IDs\n"
    for msg in messages:
        define_name = f"{msg['name'].upper()}_ID"
        header_content += f"#define {define_name:<35} 0x{msg['id']:03X}\n"
    
    header_content += "\n"
    
    # Generate message structures
    header_content += "// Message Structures\n"
    for msg in messages:
        struct_name = f"{msg['name']}_t"
        header_content += f"typedef struct {{\n"
        
        for signal in msg['signals']:
            # Determine C data type based on bit length and signedness
            if signal['length'] <= 8:
                c_type = "int8_t" if signal['signed'] else "uint8_t"
            elif signal['length'] <= 16:
                c_type = "int16_t" if signal['signed'] else "uint16_t"
            elif signal['length'] <= 32:
                c_type = "int32_t" if signal['signed'] else "uint32_t"
            else:
                c_type = "uint64_t"  # Fallback for large signals
            
            # Add scaling/offset info as comment
            comment_parts = []
            if signal['scale'] != 1.0:
                comment_parts.append(f"scale={signal['scale']}")
            if signal['offset'] != 0.0:
                comment_parts.append(f"offset={signal['offset']}")
            if signal['unit']:
                comment_parts.append(f"unit={signal['unit']}")
            
            comment = f"  // {', '.join(comment_parts)}" if comment_parts else ""
            
            header_content += f"    {c_type} {signal['name'].lower()};{comment}\n"
        
        header_content += f"}} {struct_name};\n\n"
    
    # Generate receiver mapping for CAN system
    header_content += "// Receiver Mapping (for CAN system routing)\n"
    all_receivers = set()
    for msg in messages:
        for signal in msg['signals']:
            all_receivers.update(signal['receivers'])
    
    for receiver in sorted(all_receivers):
        if receiver.strip():
            header_content += f"// {receiver} receives:\n"
            for msg in messages:
                has_signals = any(receiver in signal['receivers'] for signal in msg['signals'])
                if has_signals:
                    header_content += f"//   {msg['name']} (0x{msg['id']:03X})\n"
            header_content += "\n"
    
    # Generate raw DBC data array
    header_content += f"// Raw DBC data for runtime parsing\n"
    
    # Read the DBC file and convert to byte array
    try:
        with open(dbc_filename, 'rb') as f:
            dbc_data = f.read()
        
        header_content += f"const unsigned char {dbc_base_name}_dbc[] = {{\n"
        
        # Add bytes in groups of 12 for readability
        for i, byte in enumerate(dbc_data):
            if i % 12 == 0:
                header_content += "  "
            header_content += f"0x{byte:02x}"
            if i < len(dbc_data) - 1:
                header_content += ", "
            if i % 12 == 11 and i < len(dbc_data) - 1:
                header_content += "\n"
        
        header_content += f"\n}};\nconst unsigned int {dbc_base_name}_dbc_len = {len(dbc_data)};\n\n"
        
    except Exception as e:
        print(f"Warning: Could not read DBC file for byte array generation: {e}")
        header_content += f"// Error: Could not include raw DBC data\n\n"
    
    header_content += f"#endif // {base_name}_H\n"
    
    # Write file
    try:
        with open(output_file, 'w') as f:
            f.write(header_content)
        print(f"Generated {output_file}")
        return True
    except Exception as e:
        print(f"Error writing file: {e}")
        return False

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python simple_dbc_parser.py <input.dbc> <output.h>")
        sys.exit(1)
    
    dbc_file = sys.argv[1]
    output_file = sys.argv[2]
    
    print(f"Parsing {dbc_file}...")
    messages = parse_dbc_file(dbc_file)
    
    if messages is None:
        print("Failed to parse DBC file")
        sys.exit(1)
    
    print(f"Found {len(messages)} messages:")
    for msg in messages:
        print(f"  - {msg['name']} (0x{msg['id']:03X}) with {len(msg['signals'])} signals")
    
    print(f"\nGenerating {output_file}...")
    if generate_header(messages, output_file, dbc_file):
        print("Success! Auto-generated header ready for integration.")
    else:
        print("Failed to generate header")
        sys.exit(1)