#ifndef RENNSSELAERMOTORSPORT_WHEEL_LOCATION_H
#define RENNSSELAERMOTORSPORT_WHEEL_LOCATION_H

typedef enum {
    FRONT_LEFT,
    FRONT_RIGHT,
    BACK_LEFT,
    BACK_RIGHT
} WHEEL_LOCATION;

#endif // RENNSSELAERMOTORSPORT_WHEEL_LOCATION_H
